sudo: required

services:
- docker

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"
    - DOCKER_USERNAME: napstr
    - secure: "Phduak3SfZHvKw2klT7ckqUj/ySaYFDtE7DnsWjHqc4Q8jVCxu2g+kx6IfLNweu/lslH1eCDOmwjo5AVIuO9YE2TqsJXEWkzkJstThJYWyfjzAyOIvowjSC7KbaT0cu6RjzHsCOYRoTBZbrb7LZjxnN1NHKdThbuRgYnENba/nltlkt1+H6b6boTgghLH1gt0F5gdrZAhn+TmoZSpTr1ioTF5OVPtW+wgH/ATPXGpxyejDOeqcL110rZbtvVXQH8U4XJSl8nMkvOHe0ZyR7/s1xNF9hbhHi851OxEo34FRoRf7BXk8jzKN3KQHcDyZ0AN9Run0q/IyKgyyfDX9V1+FTJvfjrBeymbjjZ/kGcY45LeaBPsQxH+qHQAJjLtiNXyYkLRf3mp1/SW6wm7H83T9x4kc6+x9eRPIRUOscmx8jLTt0jfmQdIhcJ/B9smr8sIw4hAWZQWLI/oxuNBD3Fj93nTWmHRFC27exar9Gn+0otvOEcfftYfnWKBQUxcUe953rrP57KoXV5pF493plRN+yUr4Se5uB17aLZEOxO2O2W3suO+kFb3yD3y9tFjLpc9K/t9I3tppU/N/2Y7tn7p3fYtXZIkEh77ab2ovtOPC7h6giXFZWMrqN007pkT8bndDrSG9pVB/8HYcrW9MW80VMK/jjgiTAanldyBdgX+Y8="

language: java

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - ".gradle/wrapper"
    - ".gradle/caches"

stages:
  - build & publish


jobs:
  fast_finish: true
  include:
    - stage: build & publish
      jdk: openjdk10
      script:
        - java -Xmx32m -version
        - ./gradlew build --info
        - IMAGE_TAG=$(echo ${TRAVIS_BRANCH} | sed -e 's/\//_/g')
        - echo $IMAGE_TAG
        - IMAGE_NAME=$DOCKER_USERNAME/baymax:$IMAGE_TAG
        - docker run --rm --privileged multiarch/qemu-user-static:register
        - docker build -t "$IMAGE_NAME" -f docker/Dockerfile .
        - docker build -t "$IMAGE_NAME-arm64v8" -f docker/Dockerfile.arm64v8 .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
        - docker push $IMAGE_NAME
        - docker push $IMAGE_NAME-arm64v8
        - docker logout
