sudo: required

addons:
  sonarcloud:
    organization: "napstr-github"

services:
- docker

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"
    - DOCKER_USERNAME: napstr
    - secure: "F+0NwLNWaIM8TAJf1fMl1MmvJegMQw/dCJn5qcktRaAA/uqi6EzJ+nDI8Xx/5pzkS/dxpvyUdJWox8HUL/jIf+YH8Cv/IY0DGFKBYw41ol0rkhpUIoXc/QMvQg7xDk3zfyK2C5SBWBVdoiuhJIe9IKNTPkWer47IC3yN220nztFjcnL2KK2S7lNxLLJ12y0t6dQB9Ba1X+HfeHnjbvwnxYnp24F9IdbGCQ1UT35SxQsKXMmD1/p07Fa9G4T2WJSGO4inxCCEvlHATP0SBwTWhkWshefhOdN3vMPEs282dYcGFW5zfvycyW/F0wcAV0FgXlUdrZicNc8otkD+JQePYYLfIxK4JUC0ib90x/gop8pD2mVZaTVX6rTR4YVE7goftFokEJIEZlEDtY6Hmaxkg9QZ0ppuLxrSSnjeMSPXuY31Iw35FebsJvEQmPhyHVvGkW1hYM1I7ZOcT7SUm434+00Au5EVdHkv7qRo62QJzWBgiUFpj6fRJazAIOw5WcP3VgKAuZ7bPFtHY+WBGvK0B+BTkvNC1TUlVYLpFr9UixBT+BIq+cN2tbYZPErdOro3S/ztxh5bcbsR/SFpqKZt09HcIGWT7stsvCtRG3Qabgkq8x+UsWxkOHlVr5SyJxh2TgrVHuZCxa2glWcbQCSgBdczWjoSrtPRSqVPJnm6KYg="
    - secure: "JthIo32PJJX7+/jZV5C8fiMyWLiXJuG7oPNf47S4Xnvc+6C2qTsGvqTfxh5v42fU3MI+4MImKBpc+fenSqw18eRQIFd4YmRcwZX79k6/Qo5fdSmE6qTjVuVRm9hDRORG39yvGuDaI2i/B7VYyy6Y0IX1a+mp4V12tfqOc2ZKAr6sVyFvMHTFTOFAW0pa5QfvLx+aNw1xElNHqpG74wSzP3QkWcYjxVDYPOXUxn36Fi0VQhhwZ4rdnl0t5JrYxePeIUVPC/YOGiPCOBrJQeX15zlgMcapV34pKG57Qy5AhWPPDGGsTan5NFouAL5+9PecpsWV80rKq9BGloeLzrDdFbRjqwLEMPUQcfCg/jTsPffGVgqT/iQ3hwlLnBANuNk8tAYG6uxtzYDMhH+NWvH+LU7c/M95pnt+m+64C6HcJopo5Aw+3hix++aR6b5Hgi6lTyyen1n1HOJCklZHx4bXM5zBPqB5o6ekBoJGC7Xj0eWuWkkm7c3+qpcMmKnc0CuWQ7FMB1Pbuz7zxunK7F5oa6Qo7V4TMCw86gjg1QgZ2wMnEw3mhoVYtxvYcAuAArLZt74NLvpsPIH3Iy2qssK5PcSeV9s4G4GrD3k8AwyrJAfhI91WZe1oHkNNaxdMTbZtxYwScyzZBSd5QXkfLvUa5u3O70KRw7OaAP+SH/78vI0="

language: java

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - ".gradle/wrapper"
    - ".gradle/caches"
    - "$HOME/.sonar/cache"

stages:
  - sonar
  - build & publish


jobs:
  fast_finish: true
  include:
    - stage: sonar
      jdk: openjdk10
      before_script:
      #for full sonar cloud blame information
        - git fetch --depth=10000
      script:
        - ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=napstr-github -Dsonar.login=$SONAR_TOKEN
    - stage: build & publish
      jdk: openjdk10
      script:
        - java -Xmx32m -version
        - ./gradlew build --info
        - IMAGE_TAG=$(echo ${TRAVIS_BRANCH} | sed -e 's/\//_/g')
        - echo $IMAGE_TAG
        - IMAGE_NAME=$DOCKER_USERNAME/baymax:$IMAGE_TAG
        - docker build -t "$IMAGE_NAME" -f docker/Dockerfile .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
        - docker push $IMAGE_NAME
        - docker logout
