sudo: required

addons:
  sonarcloud:
    organization: "napstr-github"

services:
- docker

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"
    - DOCKER_USERNAME: napstr
    - secure: "HxgB5uBqRFZp75A0xXi8x2crBDgZ+9JoTW4gOMRbTK0F/dzuta6r/nKCDku7SOVUbwzTQidZif9gHxLxZuwPU+M0yEPTzipT3mtgXAnzZmKUYorxcGQZ0FaaJ8AmeqUdIFe9lZStQm3yEkAyhRzRNfbtxnwGmEIizJ3Odo2TrCJJLdCOEHhZn//CXRZkjWkQkIBpUeevNouwDFg8eU2oFaKiWNAgSALFIaFnBoZsTL7yzOIvkSNhUcMfN4N9HHzjTJav9eHvG/NEgcVCbtJ1PdQtS8a3DvKMH0XmboUipUf8zH9rzA6DI7l2doD7K/dAjyTc7lBTyOkPxJNMlgm/UvP6iWFYsJHCVcM/C3hmiRFfd9b7ciBGlYqtDY5R5jhlWPfKPP/gkeboIoQcrpk2k4DDWcCBKUCvx7e0Ph9F0OhUjoh9fBqxY+S5YOSWuTEVxD4xuVlhlIEbAiQyVjnzGddM3G/9LKB1gQtZak6yrIJ+AoqFnHf7twx2y11a2wTMc4i75p15cGd1QBFfCYjr+JoYOUf9UUZM246LmWAyzTeT8FIVSfPgd0v5w7otur41Uye6o5x1hyyvkQxSSOJFA2f9nlkmYdnddkhaoiq+TH0LTFAji+UwoBhAhr78S69hkHvOPG9P0Sby2zAItTv4HM7v0nNfLXUSRgVw6GbGM0s="
    - secure: "JthIo32PJJX7+/jZV5C8fiMyWLiXJuG7oPNf47S4Xnvc+6C2qTsGvqTfxh5v42fU3MI+4MImKBpc+fenSqw18eRQIFd4YmRcwZX79k6/Qo5fdSmE6qTjVuVRm9hDRORG39yvGuDaI2i/B7VYyy6Y0IX1a+mp4V12tfqOc2ZKAr6sVyFvMHTFTOFAW0pa5QfvLx+aNw1xElNHqpG74wSzP3QkWcYjxVDYPOXUxn36Fi0VQhhwZ4rdnl0t5JrYxePeIUVPC/YOGiPCOBrJQeX15zlgMcapV34pKG57Qy5AhWPPDGGsTan5NFouAL5+9PecpsWV80rKq9BGloeLzrDdFbRjqwLEMPUQcfCg/jTsPffGVgqT/iQ3hwlLnBANuNk8tAYG6uxtzYDMhH+NWvH+LU7c/M95pnt+m+64C6HcJopo5Aw+3hix++aR6b5Hgi6lTyyen1n1HOJCklZHx4bXM5zBPqB5o6ekBoJGC7Xj0eWuWkkm7c3+qpcMmKnc0CuWQ7FMB1Pbuz7zxunK7F5oa6Qo7V4TMCw86gjg1QgZ2wMnEw3mhoVYtxvYcAuAArLZt74NLvpsPIH3Iy2qssK5PcSeV9s4G4GrD3k8AwyrJAfhI91WZe1oHkNNaxdMTbZtxYwScyzZBSd5QXkfLvUa5u3O70KRw7OaAP+SH/78vI0="

language: java

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle/wrapper"
    - "$HOME/.gradle/caches"
    - "$HOME/.sonar/cache"

stages:
  - sonar
  - build & publish


jobs:
  fast_finish: true
  include:
    - stage: sonar
      jdk: openjdk11
      before_script:
      #for full sonar cloud blame information
        - git fetch --depth=10000
      script:
        - ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=napstr-github -Dsonar.login=$SONAR_TOKEN
    - stage: build & publish
      jdk: openjdk11
      script:
        - java -Xmx32m -version
        - ./gradlew build --info
        - IMAGE_TAG=$(echo ${TRAVIS_BRANCH} | sed -e 's/\//_/g')
        - echo $IMAGE_TAG
        - IMAGE_NAME=$DOCKER_USERNAME/baymax:$IMAGE_TAG
        - docker build -t "$IMAGE_NAME" -f docker/Dockerfile .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
        - docker push $IMAGE_NAME
        - docker logout
